#!/bin/bash
# Master script to submit all SNP heritability and twin estimates
# Usage: bash submit_all_twin_snp.sh [--methods METHOD_LIST] [--partition NAME] [--dry-run]
#
# Phase 0 canonicalizes subject IDs in every input file the jobs read
# (summary/prep_iids.sh -> $IIDFIX, default /scratch.global/coffm049/abcdEsts).
# The per-chunk configs generated by FCs/make_configs.py then read their
# template from there, so jobs see one consistent ID namespace.

set -euo pipefail

REPO=${REPO:-/users/4/coffm049/papers/functionalBrainHerit}
METHODS="AdjHE GCTA HEreg"
PARTITION=""
DRY_RUN=false

while [ $# -gt 0 ]; do
  case "$1" in
    --methods) METHODS=$2; shift 2 ;;
    --partition) PARTITION=$2; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    *) echo "Unknown: $1"; exit 1 ;;
  esac
done

cd "$REPO"
mkdir -p logs

# Normalized copies + rewritten configs land here. Summary/prep_iids.sh creates
# it; FCs/*/submit.sh and SA/SLURM_*.sh look here first and fall back to the
# in-repo template when no copy exists.
IIDFIX=${IIDFIX:-/scratch.global/coffm049/abcdEsts}
export IIDFIX

echo "=== Pre-normalizing subject IDs ==="
FC_TEMPLATES=(FCs/gordon/feExample2.json      FCs/gordon/reExample2.json
              FCs/gordon/gctaExample.json     FCs/gordon/heExample.json
              FCs/probaConns/feExample2.json  FCs/probaConns/reExample2.json
              FCs/probaConns/gctaExample.json FCs/probaConns/heExample.json)
SA_TEMPLATES=(SA/AdjHE_FE_wo_total.json SA/AdjHE_RE.json SA/AdjHE_RE_wo_total.json
              SA/GCTA.json SA/GCTA_wo_total.json SA/HE.json)

if [ "$DRY_RUN" = true ]; then
  echo "  Would run: bash summary/prep_iids.sh ${FC_TEMPLATES[*]} ${SA_TEMPLATES[*]}"
else
  source /users/4/coffm049/miniconda3/etc/profile.d/conda.sh
  conda activate MASH
  # Exits non-zero if any input copy fails verification, which aborts this
  # script before a single job is submitted rather than silently joining
  # normalized ids against un-normalized phenotypes.
  bash summary/prep_iids.sh "${FC_TEMPLATES[@]}" "${SA_TEMPLATES[@]}"
  echo ""
fi

echo "=== Submitting SNP estimates ==="
for METHOD in $METHODS; do
  if [ "$METHOD" = "AdjHE" ]; then
    # AdjHE has FE and RE variants
    echo "--- Submitting AdjHE-FE for Gordon ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/gordon/submit.sh AdjHE FE"
    else
      bash FCs/gordon/submit.sh AdjHE FE
    fi

    echo "--- Submitting AdjHE-RE for Gordon ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/gordon/submit.sh AdjHE RE"
    else
      bash FCs/gordon/submit.sh AdjHE RE
    fi

    echo "--- Submitting AdjHE-FE for ProbaConns ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/probaConns/submit.sh AdjHE FE"
    else
      bash FCs/probaConns/submit.sh AdjHE FE
    fi

    echo "--- Submitting AdjHE-RE for ProbaConns ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/probaConns/submit.sh AdjHE RE"
    else
      bash FCs/probaConns/submit.sh AdjHE RE
    fi
  elif [ "$METHOD" = "GCTA" ]; then
    # GCTA has no FE/RE variants - pass GCTA as KIND
    echo "--- Submitting GCTA for Gordon ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/gordon/submit.sh GCTA GCTA"
    else
      bash FCs/gordon/submit.sh GCTA GCTA
    fi

    echo "--- Submitting GCTA for ProbaConns ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/probaConns/submit.sh GCTA GCTA"
    else
      bash FCs/probaConns/submit.sh GCTA GCTA
    fi
  elif [ "$METHOD" = "HEreg" ]; then
    # HEreg has no FE/RE variants - pass HEreg as KIND
    echo "--- Submitting HEreg for Gordon ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/gordon/submit.sh HEreg HEreg"
    else
      bash FCs/gordon/submit.sh HEreg HEreg
    fi

    echo "--- Submitting HEreg for ProbaConns ---"
    if [ "$DRY_RUN" = true ]; then
      echo "  Would run: bash FCs/probaConns/submit.sh HEreg HEreg"
    else
      bash FCs/probaConns/submit.sh HEreg HEreg
    fi
  fi
done

echo "--- Submitting SA estimates ---"
for M in $METHODS; do
  case $M in
    AdjHE)
      # three variants: results/SA/AdjHE_RE.csv (w_total) is read by
      # 03_plot_sa_horizontal.R, 04_compare_r2.R, 04b_h2_SA_correlation.py
      # and 02d_brain_sa_total.py; AdjHE_RE_wo_total.csv by 01 and 04.
      # AdjHE_FE_wo_total.csv is the SA AdjHE-FE counterpart of
      # FCs/*/feExample2.json, so AdjHE-FE can be reported for all 3 atlases.
      echo "Submitting SA AdjHE-FE + AdjHE-RE (with + without totalNetworkSurface)..."
      if [ "$DRY_RUN" = true ]; then
        echo "  Would run: sbatch SA/SLURM_AdjHE_FE_wo_total.sh"
        echo "  Would run: sbatch SA/SLURM_AdjHE_RE_with_total.sh"
        echo "  Would run: sbatch SA/SLURM_AdjHE_RE_wo_total.sh"
      else
        sbatch SA/SLURM_AdjHE_FE_wo_total.sh
        sbatch SA/SLURM_AdjHE_RE_with_total.sh
        sbatch SA/SLURM_AdjHE_RE_wo_total.sh
      fi ;;
    GCTA) echo "Submitting SA GCTA (+ wo_total variant)..."
          if [ "$DRY_RUN" = true ]; then
            echo "  Would run: sbatch SA/SLURM_GCTA.sh"
            echo "  Would run: sbatch SA/SLURM_GCTA_wo_total.sh"
          else
            sbatch SA/SLURM_GCTA.sh
            sbatch SA/SLURM_GCTA_wo_total.sh
          fi ;;
    HEreg) echo "Submitting SA HEreg..."; [ "$DRY_RUN" = true ] && echo "  Would run: sbatch SA/SLURM_HEreg.sh" || sbatch SA/SLURM_HEreg.sh ;;
  esac
done

echo ""
echo "=== Submitting Twin estimates (conda env: twinEst) ==="
if [ "$DRY_RUN" = true ]; then
  echo "  Would run: sbatch FCs/gordon/twinEsts.SLURM"
  echo "  Would run: sbatch FCs/probaConns/twinEsts.SLURM"
  echo "  Would run: sbatch SA/twinEsts/estimate.SLURM"
else
  echo "Submitting Gordon twins..."
  sbatch FCs/gordon/twinEsts.SLURM
  echo "Submitting ProbaConns twins..."
  sbatch FCs/probaConns/twinEsts.SLURM
  echo "Submitting SA twins..."
  sbatch SA/twinEsts/estimate.SLURM
fi

echo ""
echo "Done. Check job queue with: squeue -u \$USER"